[data]
git-tree-sha1 = "f39dbf6bbe7594536e73e62cffae2b6f9c0145ed"
lazy = true

    [[data.download]]
    url = "https://github.com/nflverse/NFLData.jl/raw/main/data/data.tar.gz"
    sha256 = "eca74a33dbaf875c3f55f55e08967d1564bf017fe8be7c9513c4902a72da921b"