name = "NFLData"
uuid = "38e18452-fdda-4cae-b91e-088906595f57"
authors = ["John Edwards"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
